version: '3.3'

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/nginx/increase-timeout.conf:/etc/nginx/conf.d/increase-timeout.conf:ro
      - ./services/nginx/increase-upload-limit.conf:/etc/nginx/conf.d/increase-upload-limit.conf:ro

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile-prod
    restart: always
    environment:
      - VIRTUAL_HOST=app-staging.terasys.com
      - VIRTUAL_PORT=3000