version: '3.3'


services:

  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  db:
    image: mongo:3.4
    restart: always
    volumes:
      - db_data_dev:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./services/api:/code
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=api.terasys.lh
      - VIRTUAL_PORT=4000

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./services/app:/code
    ports:
      - "35729:35729"
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=app.terasys.lh,www.terasys.lh
      - VIRTUAL_PORT=3000

volumes:
  db_data_dev: