FROM node:10-alpine

RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]

WORKDIR /code
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build:prod

EXPOSE 4000

USER node

CMD ["npm", "run", "serve:prod"]
